### ISSUE TITLE
Calling a component causes an error not found

### ISSUE THREAD

**Issue by clearsitedesigns** [ukneeq/foundation-apps-seed#1]
I've attempted to call a panel, and accordion, and get not found when calling these items. I suspect it's trying to go back to the path components/name/name.html. - but the app can't find the actual component building pieces that are part of zf-angular foundation?
- Attempted to create a slide out panel component.
  http://foundation.zurb.com/apps/docs/#!/panel

**Comment by ukneeq** [comment]
Actually I discovered this same thing earlier today. I had a typo in the gulp.js that prevented the foundation angular components from being copied over. Did you pull the latest code? This commit should have had the fix: https://github.com/ukneeq/foundation-apps-seed/commit/d0983d7ce0f280a578c8a9884b8cbc286434d048#diff-b9e12334e9eafd8341a6107dd98510c9

Let me know if that did the trick for you.

**Comment by ukneeq** [comment]
Actually looks like I corrected the typo but forgot to correct the location that foundation expects the template files to be in. It should be fixed now if you pull the latest code. 

https://github.com/ukneeq/foundation-apps-seed/commit/948b746da0024c8ceaa438c8b5023bd205ce426a

**Comment by ukneeq** [comment]
Tested with the latest commit in last comment and it is working.
